version: "2.1"

services:
  audio:
    image: balenablocks/audio
    privileged: true
    ports:
      - 4317:4317
    restart: always
  audio-webapp:
    build: ./audio-webapp
    ports:
      - "80:80"
    restart: always
  display:
    build: ./display
    privileged: true
    restart: no