version: "2.1"

services:
  wifi-connect:
    image: balenablocks/wifi-connect:rpi
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
  display:
    build: ./display
    privileged: true
    restart: no    
  audio:
    image: balenablocks/audio
    privileged: true
    ports:
      - 4317:4317
    restart: always
  audio-webapp:
    build: ./audio-webapp
    ports:
      - "80:80"
    restart: always

