FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.8 as builder

RUN install_packages gstreamer1.0-tools \
                        gstreamer1.0-plugins-base \
                        gstreamer1.0-plugins-good \
                        gstreamer1.0-pulseaudio 

RUN python3 -m pip install flask                        

ENV PULSE_SERVER=tcp:localhost:4317

WORKDIR /usr/src/app
COPY sound/ sound/
COPY templates/ templates/
COPY main.py main.py

CMD ["python3", "main.py"]