FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN install_packages python3 \
                     python3-pip \
                     python3-setuptools \
                     python3-rpi.gpio \
                     python3-spidev \
                     python3-pillow \
                     python3-numpy 

RUN pip3 install st7789

WORKDIR /usr/src/app

COPY main.py main.py
COPY images/ images

CMD ["python3", "main.py"]